//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class battle_data
    {
        
        public uint id;
        
        public int armor_piercing;
        
        public int critical_chance;
        
        public int critical_rate;
        
        public int hp;
        
        public int def;
        
        public System.Collections.Generic.Dictionary<string, int> k_hurt;
        
        public object diy_obj;
    }
    
    public class battle_datas
    {
        
        private static System.Collections.Generic.Dictionary<string, battle_data> m_records;
        
        public static System.Collections.Generic.Dictionary<string, battle_data> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, battle_data>)Foundations.Excels.ExcelAnalyzer.init("battle_data");
            }
        }
        
        public static bool TryGetValue(string key, out battle_data record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("battle_data", key, out record);
        }
    }
}
