//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class buff_info
    {
        
        public uint id;
        
        public uint sub_id;
        
        public string name = "";
        
        public int stack_max;
        
        public int stack_time;
        
        public System.Collections.Generic.List<string> test_list;
        
        public Foundations.Excels.HaHa test_diy;
    }
    
    public class buff_infos
    {
        
        private static System.Collections.Generic.Dictionary<string, buff_info> m_records;
        
        public static System.Collections.Generic.Dictionary<string, buff_info> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, buff_info>)Foundations.Excels.ExcelAnalyzer.init("buff_info");
            }
        }
        
        public static bool TryGetValue(string key, out buff_info record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("buff_info", key, out record);
        }
    }
}
