//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class camp_coin
    {
        
        public uint id;
        
        public string name = "";
        
        public string icon = "";
        
        public object diy_obj;
    }
    
    public class camp_coins
    {
        
        private static System.Collections.Generic.Dictionary<string, camp_coin> m_records;
        
        public static System.Collections.Generic.Dictionary<string, camp_coin> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, camp_coin>)Foundations.Excels.ExcelAnalyzer.init("camp_coin");
            }
        }
        
        public static bool TryGetValue(string key, out camp_coin record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("camp_coin", key, out record);
        }
    }
}
