//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class caravan_body
    {
        
        public uint id;
        
        public uint rank;
        
        public string name = "";
        
        public string view = "";
        
        public System.Collections.Generic.Dictionary<string, int> k_hurt;
        
        public System.Collections.Generic.List<uint> work_id;
        
        public float wheel_to_caravan_dis;
        
        public int hp;
        
        public int def;
        
        public int weight;
        
        public System.Collections.Generic.Dictionary<string, int> device_slots;
        
        public object diy_obj;
    }
    
    public class caravan_bodys
    {
        
        private static System.Collections.Generic.Dictionary<string, caravan_body> m_records;
        
        public static System.Collections.Generic.Dictionary<string, caravan_body> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, caravan_body>)Foundations.Excels.ExcelAnalyzer.init("caravan_body");
            }
        }
        
        public static bool TryGetValue(string key, out caravan_body record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("caravan_body", key, out record);
        }
    }
}
