//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class caravan_slot
    {
        
        public uint body_id;
        
        public string bone_name = "";
        
        public Foundations.Excels.Slot_Type slot_type;
        
        public uint device_device_id;
        
        public uint device_device_sub_id;
    }
    
    public class caravan_slots
    {
        
        private static System.Collections.Generic.Dictionary<string, caravan_slot> m_records;
        
        public static System.Collections.Generic.Dictionary<string, caravan_slot> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, caravan_slot>)Foundations.Excels.ExcelAnalyzer.init("caravan_slot");
            }
        }
        
        public static bool TryGetValue(string key, out caravan_slot record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("caravan_slot", key, out record);
        }
    }
}
