//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class device_tag
    {
        
        public uint id;
        
        public string tag_name = "";
        
        public object diy_obj;
    }
    
    public class device_tags
    {
        
        private static System.Collections.Generic.Dictionary<string, device_tag> m_records;
        
        public static System.Collections.Generic.Dictionary<string, device_tag> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, device_tag>)Foundations.Excels.ExcelAnalyzer.init("device_tag");
            }
        }
        
        public static bool TryGetValue(string key, out device_tag record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("device_tag", key, out record);
        }
    }
}
