//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class device_rank
    {
        
        public uint id;
        
        public string img_name_bar = "";
        
        public string img_info_board = "";
        
        public string img_panel_rank = "";
        
        public object diy_obj;
    }
    
    public class device_ranks
    {
        
        private static System.Collections.Generic.Dictionary<string, device_rank> m_records;
        
        public static System.Collections.Generic.Dictionary<string, device_rank> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, device_rank>)Foundations.Excels.ExcelAnalyzer.init("device_rank");
            }
        }
        
        public static bool TryGetValue(string key, out device_rank record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("device_rank", key, out record);
        }
    }
}
