//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class device_cubicles
    {
        
        public uint id;
        
        public string cubicle_behaviour = "";
        
        public string icon_idle = "";
        
        public string icon_working = "";
        
        public object diy_obj;
    }
    
    public class device_cubicless
    {
        
        private static System.Collections.Generic.Dictionary<string, device_cubicles> m_records;
        
        public static System.Collections.Generic.Dictionary<string, device_cubicles> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, device_cubicles>)Foundations.Excels.ExcelAnalyzer.init("device_cubicles");
            }
        }
        
        public static bool TryGetValue(string key, out device_cubicles record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("device_cubicles", key, out record);
        }
    }
}
