//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class device_all
    {
        
        public uint id;
        
        public uint sub_id;
        
        public int rank;
        
        public string name = "";
        
        public string alt_info = "";
        
        public string icon_photo = "";
        
        public string se_broken = "";
        
        public string se_be_hit = "";
        
        public System.Collections.Generic.List<uint> device_tag;
        
        public Foundations.Excels.Device_Type device_type;
        
        public string prefeb = "";
        
        public int weight;
        
        public int size;
        
        public int base_value;
        
        public int target_counts;
        
        public int unlock_target_ticks;
        
        public System.ValueTuple<float, float> basic_range;
        
        public float init_angle_front;
        
        public float init_angle_front_top;
        
        public float init_angle_top;
        
        public float init_angle_back_top;
        
        public float init_angle_back;
        
        public bool rotate_by_car;
        
        public string behavior_script = "";
        
        public int basic_damage;
        
        public int melee_logic;
        
        public int fire_logic;
        
        public int shield_logic;
        
        public int hook_logic;
        
        public int ram_logic;
        
        public int other_logic;
        
        public System.ValueTuple<float, float> rotate_speed;
        
        public uint device_upgrade;
        
        public string ui_prefab = "";
        
        public System.Collections.Generic.List<uint> cubicles;
        
        public object diy_obj;
    }
    
    public class device_alls
    {
        
        private static System.Collections.Generic.Dictionary<string, device_all> m_records;
        
        public static System.Collections.Generic.Dictionary<string, device_all> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, device_all>)Foundations.Excels.ExcelAnalyzer.init("device_all");
            }
        }
        
        public static bool TryGetValue(string key, out device_all record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("device_all", key, out record);
        }
    }
}
