//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class device_upgrade
    {
        
        public uint id;
        
        public uint sub_id;
        
        public string name = "";
        
        public string desc = "";
        
        public string story_desc = "";
        
        public System.Collections.Generic.List<uint> incompatible;
        
        public System.Collections.Generic.List<uint> precondition;
        
        public System.Collections.Generic.Dictionary<uint, int> cost;
        
        public string script = "";
        
        public System.Collections.Generic.List<int> int_parms;
        
        public System.Collections.Generic.List<string> string_parms;
        
        public object diy_obj;
    }
    
    public class device_upgrades
    {
        
        private static System.Collections.Generic.Dictionary<string, device_upgrade> m_records;
        
        public static System.Collections.Generic.Dictionary<string, device_upgrade> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, device_upgrade>)Foundations.Excels.ExcelAnalyzer.init("device_upgrade");
            }
        }
        
        public static bool TryGetValue(string key, out device_upgrade record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("device_upgrade", key, out record);
        }
    }
}
