//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class encounter_dialog
    {
        
        public string id = "";
        
        public string title = "";
        
        public string content = "";
        
        public System.Collections.Generic.List<string> btn_content;
        
        public System.Collections.Generic.Dictionary<string, string> diy_prms;
        
        public object diy_obj;
    }
    
    public class encounter_dialogs
    {
        
        private static System.Collections.Generic.Dictionary<string, encounter_dialog> m_records;
        
        public static System.Collections.Generic.Dictionary<string, encounter_dialog> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, encounter_dialog>)Foundations.Excels.ExcelAnalyzer.init("encounter_dialog");
            }
        }
        
        public static bool TryGetValue(string key, out encounter_dialog record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("encounter_dialog", key, out record);
        }
    }
}
