//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class event_site
    {
        
        public uint id;
        
        public Foundations.Excels.Site_Type site_type;
        
        public uint monster_id;
        
        public string monster_state = "";
        
        public System.Collections.Generic.Dictionary<uint, int> monster_relic_list;
        
        public string dialogue_graph = "";
        
        public string prefeb = "";
        
        public System.ValueTuple<uint, uint> loot_list;
        
        public object diy_obj;
    }
    
    public class event_sites
    {
        
        private static System.Collections.Generic.Dictionary<string, event_site> m_records;
        
        public static System.Collections.Generic.Dictionary<string, event_site> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, event_site>)Foundations.Excels.ExcelAnalyzer.init("event_site");
            }
        }
        
        public static bool TryGetValue(string key, out event_site record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("event_site", key, out record);
        }
    }
}
