//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class game_world
    {
        
        public uint world_id;
        
        public string world_name = "";
        
        public bool can_load;
        
        public uint level;
        
        public string UI_level_index_bg = "";
        
        public string UI_RS_title_bg = "";
        
        public System.Collections.Generic.List<float> pressure_threshold;
        
        public System.Collections.Generic.List<float> pressure_growth_coef;
        
        public System.Collections.Generic.List<uint> shop_list_device;
        
        public System.Collections.Generic.List<uint> shop_list_role;
        
        public System.Collections.Generic.List<uint> shop_list_elite_relic;
        
        public System.Collections.Generic.List<uint> shop_list_relic;
        
        public object diy_obj;
    }
    
    public class game_worlds
    {
        
        private static System.Collections.Generic.Dictionary<string, game_world> m_records;
        
        public static System.Collections.Generic.Dictionary<string, game_world> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, game_world>)Foundations.Excels.ExcelAnalyzer.init("game_world");
            }
        }
        
        public static bool TryGetValue(string key, out game_world record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("game_world", key, out record);
        }
    }
}
