//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class melee_logic
    {
        
        public uint logic_id;
        
        public int cd;
        
        public bool can_blaze;
        
        public float sharpness_min;
        
        public System.Collections.Generic.List<float> sharpness_range;
        
        public System.Collections.Generic.List<float> sharpness_dmg_range;
        
        public float sharpness_loss;
        
        public float sharpness_recover;
        
        public System.Collections.Generic.List<string> ui_atk_horizontal_anim;
        
        public System.Collections.Generic.List<string> ui_atk_vertical_anim;
        
        public string SE_attack_begin = "";
        
        public string SE_grinding = "";
        
        public int atk_event_num;
        
        public System.ValueTuple<float, float> hit_period;
        
        public System.Nullable<System.ValueTuple<float, float>> hit_period_2;
        
        public float hit_box_offset;
        
        public float atk_part_speed;
        
        public float attack_charge_weight;
        
        public float attack_charge_speed;
        
        public int ui_charge_trigger_ticks;
        
        public System.Collections.Generic.List<float> job_speed;
        
        public System.Collections.Generic.Dictionary<string, int> damage;
        
        public float knockback_ft;
        
        public object diy_obj;
    }
    
    public class melee_logics
    {
        
        private static System.Collections.Generic.Dictionary<string, melee_logic> m_records;
        
        public static System.Collections.Generic.Dictionary<string, melee_logic> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, melee_logic>)Foundations.Excels.ExcelAnalyzer.init("melee_logic");
            }
        }
        
        public static bool TryGetValue(string key, out melee_logic record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("melee_logic", key, out record);
        }
    }
}
