//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class mg_scene
    {
        
        public uint id;
        
        public uint sub_id;
        
        public uint monster_id;
        
        public System.Nullable<bool> is_elite;
        
        public string init_state = "";
        
        public string end_state = "";
        
        public UnityEngine.Vector2 pos;
        
        public float pos_rnd_radius;
        
        public int count_max;
        
        public System.Nullable<UnityEngine.Vector2> generate_count_area;
        
        public int tension_min;
        
        public int tension_max;
        
        public UnityEngine.Vector2 spawn_init;
        
        public UnityEngine.Vector2 spawn_threshold;
        
        public float k_distance;
        
        public float k_time;
        
        public float kill_pressure;
        
        public int tide_count_addtion;
        
        public float tide_time_addtion;
        
        public object diy_obj;
    }
    
    public class mg_scenes
    {
        
        private static System.Collections.Generic.Dictionary<string, mg_scene> m_records;
        
        public static System.Collections.Generic.Dictionary<string, mg_scene> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, mg_scene>)Foundations.Excels.ExcelAnalyzer.init("mg_scene");
            }
        }
        
        public static bool TryGetValue(string key, out mg_scene record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("mg_scene", key, out record);
        }
    }
}
