//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class mg_weather
    {
        
        public uint id;
        
        public uint sub_id;
        
        public uint monster_id;
        
        public string init_state = "";
        
        public UnityEngine.Vector2 pos;
        
        public float pos_rnd_radius;
        
        public int count_max;
        
        public System.Nullable<UnityEngine.Vector2> generate_count_area;
        
        public UnityEngine.Vector2 spawn_init;
        
        public UnityEngine.Vector2 spawn_threshold;
        
        public float k_time;
        
        public object diy_obj;
    }
    
    public class mg_weathers
    {
        
        private static System.Collections.Generic.Dictionary<string, mg_weather> m_records;
        
        public static System.Collections.Generic.Dictionary<string, mg_weather> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, mg_weather>)Foundations.Excels.ExcelAnalyzer.init("mg_weather");
            }
        }
        
        public static bool TryGetValue(string key, out mg_weather record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("mg_weather", key, out record);
        }
    }
}
