//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class monster
    {
        
        public uint id;
        
        public string name = "";
        
        public string sub_table_name = "";
        
        public string sub_table_key = "";
        
        public string SE_attack = "";
        
        public int hp;
        
        public int def;
        
        public float mass;
        
        public bool is_block_car;
        
        public bool is_elite;
        
        public System.Collections.Generic.Dictionary<string, int> diy_atk;
        
        public int ts;
        
        public int dodge;
        
        public float base_speed;
        
        public float max_force;
        
        public bool is_follow;
        
        public System.Collections.Generic.Dictionary<string, int> k_hurt;
        
        public string monster_view = "";
        
        public string monster_behaviour_tree = "";
        
        public int fire_logic;
        
        public float feedback;
        
        public System.Collections.Generic.Dictionary<uint, float> loot_list;
        
        public System.Collections.Generic.List<string> death_vfx;
        
        public System.Collections.Generic.List<string> enemy_tags;
        
        public System.Collections.Generic.List<uint> component;
        
        public System.Collections.Generic.Dictionary<string, int> sub_monsters;
        
        public System.Collections.Generic.Dictionary<string, string> diy_prms;
        
        public object diy_obj;
    }
    
    public class monsters
    {
        
        private static System.Collections.Generic.Dictionary<string, monster> m_records;
        
        public static System.Collections.Generic.Dictionary<string, monster> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, monster>)Foundations.Excels.ExcelAnalyzer.init("monster");
            }
        }
        
        public static bool TryGetValue(string key, out monster record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("monster", key, out record);
        }
    }
}
