//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class other_logic
    {
        
        public uint logic_id;
        
        public string se_1 = "";
        
        public float animevent_prct_1;
        
        public System.Collections.Generic.List<float> job_speed;
        
        public System.Collections.Generic.Dictionary<string, int> damage;
        
        public float knockback_ft;
        
        public System.Collections.Generic.Dictionary<string, string> diy_prms;
        
        public object diy_obj;
    }
    
    public class other_logics
    {
        
        private static System.Collections.Generic.Dictionary<string, other_logic> m_records;
        
        public static System.Collections.Generic.Dictionary<string, other_logic> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, other_logic>)Foundations.Excels.ExcelAnalyzer.init("other_logic");
            }
        }
        
        public static bool TryGetValue(string key, out other_logic record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("other_logic", key, out record);
        }
    }
}
