//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class plot
    {
        
        public uint group_id;
        
        public uint site_order;
        
        public int event_count;
        
        public bool ui_visible;
        
        public System.Collections.Generic.List<uint> event_list;
        
        public System.ValueTuple<float, float> event_interval;
        
        public object diy_obj;
    }
    
    public class plots
    {
        
        private static System.Collections.Generic.Dictionary<string, plot> m_records;
        
        public static System.Collections.Generic.Dictionary<string, plot> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, plot>)Foundations.Excels.ExcelAnalyzer.init("plot");
            }
        }
        
        public static bool TryGetValue(string key, out plot record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("plot", key, out record);
        }
    }
}
