//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class plot_paragraph
    {
        
        public uint map_id;
        
        public uint site_order;
        
        public float distance_to_next;
        
        public System.Collections.Generic.List<uint> event_site;
        
        public object diy_obj;
    }
    
    public class plot_paragraphs
    {
        
        private static System.Collections.Generic.Dictionary<string, plot_paragraph> m_records;
        
        public static System.Collections.Generic.Dictionary<string, plot_paragraph> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, plot_paragraph>)Foundations.Excels.ExcelAnalyzer.init("plot_paragraph");
            }
        }
        
        public static bool TryGetValue(string key, out plot_paragraph record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("plot_paragraph", key, out record);
        }
    }
}
