//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class pool_loot
    {
        
        public uint id;
        
        public System.Collections.Generic.Dictionary<uint, int> pool_loot_dic;
        
        public object diy_obj;
    }
    
    public class pool_loots
    {
        
        private static System.Collections.Generic.Dictionary<string, pool_loot> m_records;
        
        public static System.Collections.Generic.Dictionary<string, pool_loot> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, pool_loot>)Foundations.Excels.ExcelAnalyzer.init("pool_loot");
            }
        }
        
        public static bool TryGetValue(string key, out pool_loot record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("pool_loot", key, out record);
        }
    }
}
