//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class projectile
    {
        
        public uint projectile_id;
        
        public string ammo_type = "";
        
        public float speed_dmg_mod;
        
        public string detection_type = "";
        
        public float radius;
        
        public float mass;
        
        public float k_feedback;
        
        public System.Collections.Generic.List<string> path;
        
        public float propulsion_force;
        
        public float propulsion_error;
        
        public System.Collections.Generic.List<bool> exploded_by_lifetime;
        
        public float explode_radius;
        
        public int explode_dmg;
        
        public float explode_ft;
        
        public float explode_ignite;
        
        public string explode_vfx = "";
        
        public string explode_se = "";
        
        public float inertia_moment;
        
        public string rotate_rule = "";
        
        public string hit_ground_rule = "";
        
        public string hit_monster_rule = "";
        
        public string vfx_on_hit_ground = "";
        
        public string se_on_hit_ground = "";
        
        public float vfx_v_threshold;
        
        public object diy_obj;
    }
    
    public class projectiles
    {
        
        private static System.Collections.Generic.Dictionary<string, projectile> m_records;
        
        public static System.Collections.Generic.Dictionary<string, projectile> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, projectile>)Foundations.Excels.ExcelAnalyzer.init("projectile");
            }
        }
        
        public static bool TryGetValue(string key, out projectile record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("projectile", key, out record);
        }
    }
}
