//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class properties
    {
        
        public uint id;
        
        public string name = "";
        
        public int rank;
        
        public bool negative;
        
        public string desc = "";
        
        public string script = "";
        
        public System.Collections.Generic.List<int> int_parms;
        
        public System.Collections.Generic.List<float> float_parms;
        
        public object diy_obj;
    }
    
    public class propertiess
    {
        
        private static System.Collections.Generic.Dictionary<string, properties> m_records;
        
        public static System.Collections.Generic.Dictionary<string, properties> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, properties>)Foundations.Excels.ExcelAnalyzer.init("properties");
            }
        }
        
        public static bool TryGetValue(string key, out properties record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("properties", key, out record);
        }
    }
}
