//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class ram_logic
    {
        
        public uint logic_id;
        
        public string SE_hit_enemy = "";
        
        public string SE_rotate = "";
        
        public System.Collections.Generic.Dictionary<string, int> damage;
        
        public float v_threshold;
        
        public float damage_v_coef;
        
        public float ft;
        
        public float ft_v_coef;
        
        public float collision_rotate_coef;
        
        public float ui_rotate_coef;
        
        public float knock_y;
        
        public object diy_obj;
    }
    
    public class ram_logics
    {
        
        private static System.Collections.Generic.Dictionary<string, ram_logic> m_records;
        
        public static System.Collections.Generic.Dictionary<string, ram_logic> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, ram_logic>)Foundations.Excels.ExcelAnalyzer.init("ram_logic");
            }
        }
        
        public static bool TryGetValue(string key, out ram_logic record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("ram_logic", key, out record);
        }
    }
}
