//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class relic_pool
    {
        
        public uint pool_id;
        
        public uint parm_int;
        
        public int weight;
        
        public object diy_obj;
    }
    
    public class relic_pools
    {
        
        private static System.Collections.Generic.Dictionary<string, relic_pool> m_records;
        
        public static System.Collections.Generic.Dictionary<string, relic_pool> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, relic_pool>)Foundations.Excels.ExcelAnalyzer.init("relic_pool");
            }
        }
        
        public static bool TryGetValue(string key, out relic_pool record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("relic_pool", key, out record);
        }
    }
}
