//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class relic_rank
    {
        
        public uint id;
        
        public string UI_shop_bg = "";
        
        public string UI_bag_bg = "";
        
        public object diy_obj;
    }
    
    public class relic_ranks
    {
        
        private static System.Collections.Generic.Dictionary<string, relic_rank> m_records;
        
        public static System.Collections.Generic.Dictionary<string, relic_rank> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, relic_rank>)Foundations.Excels.ExcelAnalyzer.init("relic_rank");
            }
        }
        
        public static bool TryGetValue(string key, out relic_rank record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("relic_rank", key, out record);
        }
    }
}
