//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class role
    {
        
        public uint id;
        
        public string name = "";
        
        public string portrait_small = "";
        
        public string illustration_big = "";
        
        public string illustration_small = "";
        
        public string UI_Shop_Illustration_viewed = "";
        
        public int base_value;
        
        public float coma_g;
        
        public System.Collections.Generic.List<uint> properties;
        
        public System.ValueTuple<int, int> properties_num;
        
        public System.Collections.Generic.List<uint> properties_rnd;
        
        public System.Collections.Generic.List<string> lines_coma;
        
        public object diy_obj;
    }
    
    public class roles
    {
        
        private static System.Collections.Generic.Dictionary<string, role> m_records;
        
        public static System.Collections.Generic.Dictionary<string, role> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, role>)Foundations.Excels.ExcelAnalyzer.init("role");
            }
        }
        
        public static bool TryGetValue(string key, out role record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("role", key, out record);
        }
    }
}
