//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class safe_zone_event
    {
        
        public uint id;
        
        public string dialogue_graph = "";
        
        public string view_prefab = "";
        
        public string rs_desc = "";
        
        public object diy_obj;
    }
    
    public class safe_zone_events
    {
        
        private static System.Collections.Generic.Dictionary<string, safe_zone_event> m_records;
        
        public static System.Collections.Generic.Dictionary<string, safe_zone_event> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, safe_zone_event>)Foundations.Excels.ExcelAnalyzer.init("safe_zone_event");
            }
        }
        
        public static bool TryGetValue(string key, out safe_zone_event record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("safe_zone_event", key, out record);
        }
    }
}
