//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class scene_shop_group
    {
        
        public uint group_id;
        
        public System.Collections.Generic.List<string> shop_list;
        
        public object diy_obj;
    }
    
    public class scene_shop_groups
    {
        
        private static System.Collections.Generic.Dictionary<string, scene_shop_group> m_records;
        
        public static System.Collections.Generic.Dictionary<string, scene_shop_group> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, scene_shop_group>)Foundations.Excels.ExcelAnalyzer.init("scene_shop_group");
            }
        }
        
        public static bool TryGetValue(string key, out scene_shop_group record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("scene_shop_group", key, out record);
        }
    }
}
