//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class shop
    {
        
        public uint id;
        
        public Foundations.Excels.Shop_Type shop_type;
        
        public System.ValueTuple<int, int> goods_count_rnd;
        
        public System.Collections.Generic.List<System.ValueTuple<uint, int>> shop_goods_price;
        
        public System.ValueTuple<int, float, float> discount;
        
        public System.Collections.Generic.Dictionary<uint, int> goods_rnd_pool;
        
        public object diy_obj;
    }
    
    public class shops
    {
        
        private static System.Collections.Generic.Dictionary<string, shop> m_records;
        
        public static System.Collections.Generic.Dictionary<string, shop> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, shop>)Foundations.Excels.ExcelAnalyzer.init("shop");
            }
        }
        
        public static bool TryGetValue(string key, out shop record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("shop", key, out record);
        }
    }
}
