//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class shop_ui
    {
        
        public string id = "";
        
        public string name = "";
        
        public string icon = "";
        
        public object diy_obj;
    }
    
    public class shop_uis
    {
        
        private static System.Collections.Generic.Dictionary<string, shop_ui> m_records;
        
        public static System.Collections.Generic.Dictionary<string, shop_ui> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, shop_ui>)Foundations.Excels.ExcelAnalyzer.init("shop_ui");
            }
        }
        
        public static bool TryGetValue(string key, out shop_ui record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("shop_ui", key, out record);
        }
    }
}
