//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class spine_monster
    {
        
        public uint id;
        
        public string state = "";
        
        public string anim_name = "";
        
        public bool loop;
        
        public string unconsious_anim_name = "";
        
        public object diy_obj;
    }
    
    public class spine_monsters
    {
        
        private static System.Collections.Generic.Dictionary<string, spine_monster> m_records;
        
        public static System.Collections.Generic.Dictionary<string, spine_monster> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, spine_monster>)Foundations.Excels.ExcelAnalyzer.init("spine_monster");
            }
        }
        
        public static bool TryGetValue(string key, out spine_monster record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("spine_monster", key, out record);
        }
    }
}
