//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class spine_caravan
    {
        
        public uint id;
        
        public uint rank;
        
        public string state = "";
        
        public string anim_name = "";
        
        public bool loop;
    }
    
    public class spine_caravans
    {
        
        private static System.Collections.Generic.Dictionary<string, spine_caravan> m_records;
        
        public static System.Collections.Generic.Dictionary<string, spine_caravan> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, spine_caravan>)Foundations.Excels.ExcelAnalyzer.init("spine_caravan");
            }
        }
        
        public static bool TryGetValue(string key, out spine_caravan record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("spine_caravan", key, out record);
        }
    }
}
