//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class sub_monster_car
    {
        
        public uint id;
        
        public uint sub_id;
        
        public int odds;
        
        public uint carbody;
        
        public System.Collections.Generic.Dictionary<string, int> device;
        
        public string ai = "";
        
        public System.ValueTuple<int, int> hp_mod;
        
        public int dmg_mod;
        
        public object diy_obj;
    }
    
    public class sub_monster_cars
    {
        
        private static System.Collections.Generic.Dictionary<string, sub_monster_car> m_records;
        
        public static System.Collections.Generic.Dictionary<string, sub_monster_car> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, sub_monster_car>)Foundations.Excels.ExcelAnalyzer.init("sub_monster_car");
            }
        }
        
        public static bool TryGetValue(string key, out sub_monster_car record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("sub_monster_car", key, out record);
        }
    }
}
