//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class tech
    {
        
        public uint id;
        
        public string ui_name = "";
        
        public string ui_desc = "";
        
        public bool ui_visible;
        
        public bool unlocked;
        
        public uint set_tech_visible;
        
        public System.Collections.Generic.Dictionary<uint, int> cost;
        
        public string script = "";
        
        public System.Collections.Generic.List<int> int_parms;
        
        public object diy_obj;
    }
    
    public class techs
    {
        
        private static System.Collections.Generic.Dictionary<string, tech> m_records;
        
        public static System.Collections.Generic.Dictionary<string, tech> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, tech>)Foundations.Excels.ExcelAnalyzer.init("tech");
            }
        }
        
        public static bool TryGetValue(string key, out tech record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("tech", key, out record);
        }
    }
}
