//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class weather_group
    {
        
        public uint group_id;
        
        public uint sub_id;
        
        public uint weather;
        
        public System.ValueTuple<float, float> length;
        
        public System.Collections.Generic.List<System.ValueTuple<uint, int>> next;
        
        public object diy_obj;
    }
    
    public class weather_groups
    {
        
        private static System.Collections.Generic.Dictionary<string, weather_group> m_records;
        
        public static System.Collections.Generic.Dictionary<string, weather_group> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, weather_group>)Foundations.Excels.ExcelAnalyzer.init("weather_group");
            }
        }
        
        public static bool TryGetValue(string key, out weather_group record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("weather_group", key, out record);
        }
    }
}
