//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodes
{
    
    
    public class weather
    {
        
        public uint id;
        
        public string name = "";
        
        public string desc = "";
        
        public string weather_icon_path = "";
        
        public string view_prefab = "";
        
        public string mask_prefab = "";
        
        public uint monsters;
        
        public System.Collections.Generic.List<string> heal_tags;
        
        public System.ValueTuple<float, float, float> monster_HOT;
        
        public System.Collections.Generic.List<string> buff_remove;
        
        public string behaviour = "";
        
        public System.Collections.Generic.Dictionary<string, string> diy_prms;
        
        public object diy_obj;
    }
    
    public class weathers
    {
        
        private static System.Collections.Generic.Dictionary<string, weather> m_records;
        
        public static System.Collections.Generic.Dictionary<string, weather> records
        {
            get
            {
                return (System.Collections.Generic.Dictionary<string, weather>)Foundations.Excels.ExcelAnalyzer.init("weather");
            }
        }
        
        public static bool TryGetValue(string key, out weather record)
        {
            return Foundations.Excels.ExcelAnalyzer.try_get_value("weather", key, out record);
        }
    }
}
